tittle: Khalil Ahmed Halepoto
description: 👋 Hi, I’m Khalil Ahmed, an experienced IT Specialist and Service Delivery Engineer with over 6 years of expertise in IT operations, network administration, and enterprise service management.

I specialize in:

Managing cloud-based servers, enterprise portals, and critical IT infrastructure

Troubleshooting hardware, software, and network issues (LAN/WAN, switches, routers, IP phones)

Deploying and maintaining security systems, biometric devices, ATM/CDM networks, and CCTV surveillance

Automating reporting tools and monitoring IT services to ensure high availability and SLA compliance

Supporting ERP and enterprise applications like SAP and Microsoft 365
